# Generated by Django 4.0.4 on 2022-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_user_watchlist_listing_user_alter_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='auctions.listing'),
        ),
    ]
