# Generated by Django 4.0.4 on 2022-06-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_listing_alter_bid_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('home', 'Home'), ('tools', 'Tools'), ('clothes', 'Clothes'), ('toys', 'Toys')], max_length=255, null=True),
        ),
    ]
